services:
  frontend:
    build: .
    ports:
      - '5173:5173'
    volumes:
      - .:/app # 내 컴퓨터의 코드가 수정되면 도커에도 즉시 반영 (핫 리로드)
      - /app/node_modules # 컨테이너 내부의 node_modules는 보호
    environment:
      - CHOKIDAR_USEPOLLING=true # 일부 운영체제에서 파일 변경 감지를 돕는 설정
