export const PROJECTS = [
  {
    id: 1,
    title: 'E-Commerce Platform Redesign',
    status: 'In progress',
    description:
      'Complete redesign of the e-commerce platform with focus on user experience and conversion...',
    date: 'Jan 15, 2024 - Jun 30, 2024',
    members: 8,
    tasks: 12,
    statusColor: 'bg-blue-100 text-blue-700',
  },
  {
    id: 2,
    title: 'Mobile App Development',
    status: 'Completed',
    description: 'Native mobile application for iOS and Android platforms',
    date: 'Sep 1, 2023 - Dec 31, 2023',
    members: 6,
    tasks: 18,
    statusColor: 'bg-green-100 text-green-700',
  },
  {
    id: 3,
    title: 'Marketing Campaign Q1',
    status: 'Not started',
    description: 'Comprehensive marketing campaign for Q1 product launch',
    date: 'Apr 1, 2024 - Jun 30, 2024',
    members: 5,
    tasks: 0,
    statusColor: 'bg-gray-100 text-gray-700',
  },
  {
    id: 4,
    title: 'API Integration Project',
    status: 'In progress',
    description:
      'Integration of third-party APIs and microservices architecture',
    date: 'Feb 1, 2024 - May 15, 2024',
    members: 4,
    tasks: 7,
    statusColor: 'bg-blue-100 text-blue-700',
  },
  {
    id: 5,
    title: 'Data Analytics Dashboard',
    status: 'Completed',
    description:
      'Real-time analytics dashboard with advanced visualization capabilities',
    date: 'Oct 15, 2023 - Jan 20, 2024',
    members: 7,
    tasks: 15,
    statusColor: 'bg-green-100 text-green-700',
  },
  {
    id: 6,
    title: 'Customer Support Portal',
    status: 'In progress',
    description: 'Self-service customer support portal with AI-powered chatbot',
    date: 'Jan 10, 2024 - Apr 30, 2024',
    members: 5,
    tasks: 9,
    statusColor: 'bg-blue-100 text-blue-700',
  },
];
